apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retronatus-deployment-production
  namespace: production
  labels:
    app: production
spec:
  selector:
    matchLabels:
      app: production
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: production
    spec:
      containers:
       - name: retronatus
         image: hari6091/retronatus_frontend
         ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-cip-production
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: production
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-production
  namespace: production
spec:
  ingressClassName: retronatus
  rules:
  - host: production.10.49.10.47.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: front-end-cip-production
            port: 
              number: 80