apiVersion: v1
kind: Namespace
metadata:
  name: homolog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retronatus-deployment-homolog
  namespace: homolog
  labels:
    app: homolog
spec:
  selector:
    matchLabels:
      app: homolog
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: homolog
    spec:
      containers:
       - name: retronatus
         image: hari6091/retronatus_frontend
         ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-cip-homolog
  namespace: homolog
spec:
  type: ClusterIP
  selector:
    app: homolog
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-homolog
  namespace: homolog
spec:
  ingressClassName: retronatus
  rules:
  - host: homolog.10.49.10.47.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: front-end-cip-homolog
            port: 
              number: 80