apiVersion: v1
kind: Namespace
metadata:
  name: develop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retronatus-deployment-develop
  namespace: develop
  labels:
    app: develop
spec:
  selector:
    matchLabels:
      app: develop
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: develop
    spec:
      containers:
       - name: retronatus
         image: hari6091/retronatus_frontend
         ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-cip
  namespace: develop
spec:
  type: ClusterIP
  selector:
    app: develop
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-primario-develop
  namespace: develop
spec:
  ingressClassName: retronatus
  rules:
  - host: develop.10.49.10.47.nip.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: front-end-cip
            port: 
              number: 80
